### ISSUE TITLE
Import registered courses into Workday Calendar Extension

### ISSUE THREAD

**Issue by callumoriley** [mlool/workday-calendar-extension#116]
Having the extension show your schedule for registered courses would make it more usable beyond the initial course registration period. I created a working prototype of this idea using Javascript:

![image](https://github.com/mlool/workday-calendar-extension/assets/86801140/ea86eae7-b18b-4a87-b792-e31df31b8d1b)

**Comment by jaskirat-gill** [comment]
Note for devs looking into this - Should be easy by using the existing code to copy saved schedules to worklists. Should just need to add a button to the DOM like the one that exists and then call the function that makes the API calls. I believe from initial inspection the DOM structure is the same for this page and the saved schedules, maybe a few selectors might need to change

**Comment by callumoriley** [comment]
Thanks for letting me know! I'll work on making it work like that!
