### ISSUE TITLE
[Bug] Worklist to Saved Schedules sync should only sync the correct term

### ISSUE THREAD

**Issue by raymond212** [mlool/workday-calendar-extension#140]
Worklists can have courses in both terms, while saved schedules are only for one term. When syncing from a worklist to a saved schedule, the extension should only try to sync courses in the worklist that are in the same term as the target saved schedule.

**Comment by ThatNerdSquared** [comment]
Note to whoever fixes this in the future: problem is that we don't filter by term, only by worklist, when passing sections to the sync handler (see the `sections` prop when `Form` is created in `App.tsx`). should be easily solvable by adding a helper that removes all sections not in the current term before passing them into `Form`.

**Comment by jaskirat-gill** [comment]
Closing as resolved
