### ISSUE TITLE
Calendar export does not yet include the location for the classes

### ISSUE THREAD

**Issue by NeilMitra** [mlool/workday-calendar-extension#179]
It would be greatly appreciated if the calendar export feature included the classes' location (similar to the export feature on SSC) for each class when added to calendar software. Thank you!

**Comment by munr0** [comment]
I agree! I was able to do this manually by feeding chatGPT the .ics and .json schedule files to merge the locations into the .ics but still would be good to have this be automatic.

**Comment by NeilMitra** [comment]
Hello @jaskirat-gill - the issue has not been fixed yet.. Thank you for your kind understanding.

**Comment by jaskirat-gill** [comment]
Hi @NeilMitra the issue is resolved in PR #183 and is included in version 2.02
This version is available on Discord only currently for testing, and will be released on the webstore in a week or so.

**Comment by NeilMitra** [comment]
I see! My apologies for the inconvenience. Sounds great! Thank you, @jaskirat-gill!
