### ISSUE TITLE
Courses with Alternate Weeks bugs

### ISSUE THREAD

**Issue by Vaten0x** [mlool/workday-calendar-extension#24]
A crashing bug here. It looks like its because of that "(Alternate Weeks)" which in some case that seems to appear very rarely.

![Screenshot 2024-05-30 192231](https://github.com/mlool/workday-calendar-extension/assets/113562298/dc48ae60-d167-4144-b89b-23c6163584f8)

**Comment by l-currie** [comment]
Should be fixed in #22
