### ISSUE TITLE
Fix 2 term courses

### ISSUE THREAD

**Issue by mlool** [mlool/workday-calendar-extension#40]
Example BIOL 155

Connect worklist T1 T2 together
If 2 term courses is added worklist 1 it will be in worklist 1 for both terms

Behavior, only finish adding course when it is added to both T1 and T2 without conflicts
Click plus icon,
If no conflict in both terms => Can add course
If conflict => highlight the conflicting term

**Comment by l-currie** [comment]
#54 should resolve this

**Comment by mlool** [comment]
Resolved
