### ISSUE TITLE
Bug: Firefox v1.2.5 section selection

### ISSUE THREAD

**Issue by david-mcpherson** [mlool/workday-calendar-extension#52]
Selecting a section is impossible on Firefox release 1.2.5. 

![section-switch-bug](https://github.com/mlool/workday-calendar-extension/assets/89413187/ed4cff58-c145-45c9-a9c4-abb9deabedf0)

**Comment by rondnelson99** [comment]
Yeah, I'm experiencing the same thing on Firefox. I find that the "add section" button is still usable when it's flashing like this so it's possible to work around for me at least. After adding the section, it still continues flashing  and pressing cancel does not help. Reloading makes it stop flashing.

**Comment by mlool** [comment]
@david-mcpherson Have you tried with the 1.3 build?

**Comment by rondnelson99** [comment]
This is a Firefox-only issue, right? As far as I can tell, Firefox 1.3 isn't released yet, right?

**Comment by david-mcpherson** [comment]
Bug fixed by firefox release 1.3
![image](https://github.com/mlool/workday-calendar-extension/assets/89413187/be9a41d8-45ce-49c7-995e-af598512eef4)
