### ISSUE TITLE
Bug with Cancel Button on FireFox

### ISSUE THREAD

**Issue by Vaten0x** [mlool/workday-calendar-extension#68]
https://github.com/mlool/workday-calendar-extension/assets/113562298/291e950d-0f18-4356-bb85-14e0d5c43703

**Comment by jaskirat-gill** [comment]
@Vaten0x I couldnt replicate this on chrome.  Do you know if it only happens on firefox?

**Comment by Vaten0x** [comment]
Not sure how this error was made, someone mentioned it with the video on the Discord server

**Comment by Vaten0x** [comment]
I think this bug was fixed, I'll close this issue for now, i can't replicate it back on chrome either.

**Comment by Vaten0x** [comment]
Nevermind, this video was recorded using Firefox, if anyone has FireFox to test if this issue persists it'll be great.
