### ISSUE TITLE
Section popup does not close when worklist is cleared

### ISSUE THREAD

**Issue by jaskirat-gill** [mlool/workday-calendar-extension#70]
If a section popup is open, and worklist is cleared, the popup remains even though the class no longer is in the worklist. 
Ex CPSC 121 has been cleared but the popup still exists
![image](https://github.com/mlool/workday-calendar-extension/assets/60302907/c1ff76bf-a978-4129-a022-53bb553a4cca)

**Comment by l-currie** [comment]
@mlool is this one closeable?

**Comment by jaskirat-gill** [comment]
Closing because merged and fixed and after testing, original issue not occuring in latest version (1.4)
