### ISSUE TITLE
Toggle Workday slide-in animations

### ISSUE THREAD

**Issue by Rileyc2022** [mlool/workday-calendar-extension#76]
Some people were requesting this feature so I'm opening this issue. Basically when you open a new Workday page, all the panels play a staggered entrance animation.

1. They slide-in from the bottom
2. Their opacity goes from 0 -> 1

As the data is already there, this extra wait each page makes navigating the website unnecessarily slow and, well, annoying.

It'd be nice if there was a toggle in the extension where you could turn this off on all pages.

**Comment by StashC** [comment]
Hey, I think this issue is out of scope for the extension, I think it will be more of a hassle to remove these.
